### ISSUE TITLE
Resolve 404 error code for (https://github.com/ssoready/fern-config) in order to properly suggest code changes

### ISSUE THREAD

**Issue by dnich02f** [ssoready/ssoready-python#11]
Under "Contribution", the url to ssoready/fern-config (https://github.com/ssoready/fern-config) returns a 404 error code. Since it is noted that "most code changes need to be made there", I think that the url needs to be resolved. 

> Issues and PRs are more than welcome. Be advised that this library is largely autogenerated from [ssoready/fern-config](https://github.com/ssoready/fern-config). Most code changes ultimately need to be made there, not on this repo.

**Comment by ucarion** [comment]
Sorry for not noticing this earlier! This is fixed.
